export enum Routes {
  START = 'START',
  CHANGE_NAME = 'CHANGE_NAME',
  ADD_MEDICATION = 'ADD_MEDICATION',
  MEDICATION_DETAILS = 'MEDICATION_DETAILS',
  MEDICATION_HISTORY = 'MEDICATION_HISTORY',
}
